### ISSUE TITLE
adding link in data container, need title string

### ISSUE THREAD

**Issue by jimlongo56** [lokesh/lightbox2#179]
I've gotten very close, but lack the final step to make this work.

near the top of the javascript in the section where the html is built I added a div 'lb-linkContainer' which has anchor with class 'lb-link' like so.

``` html
<div id='lightboxOverlay' class='lightboxOverlay'></div><div id='lightbox' class='lightbox'><div class='lb-outerContainer'><div class='lb-container'><img class='lb-image' src='' /><div class='lb-nav'><a class='lb-prev' href='' ></a><a class='lb-next' href='' ></a></div><div class='lb-loader'><a class='lb-cancel'></a></div></div></div><div class='lb-dataContainer'><div class='lb-data'><div class='lb-details'><span class='lb-caption'></span><span class='lb-number'></span></div><div class='lb-linkContainer'><a class='lb-link'></a></div><div class='lb-closeContainer'><a class='lb-close'></a></div></div></div></div>
```

then a little further down after the prev and next click functions and before the end close function add the link function

``` javascript
this.$lightbox.find('.lb-link').on('click',function(){c.end();window.location='http://mydomain.com'});
```

Change the css by modifying the width of the lb-details and lb-close classes and adding the lb-link class

``` css
.lb-data .lb-link{
  display: block;
  float: left;
  width: 50%;
  height: 30px;
  background: url(../buyNow.png) top right no-repeat;
  text-align: left;
  outline: none;
  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=70);
  opacity: 0.7;
  -webkit-transition: opacity 0.2s;
  -moz-transition: opacity 0.2s;
  -o-transition: opacity 0.2s;
  transition: opacity 0.2s;
}
.lb-data .lb-link:hover {
  cursor: pointer;
  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
  opacity: 1;
}
```

You should now have a new image in the bar which will open the url when clicked.

What I'm missing is how to get the title data appended to my url.
In my case it is a number I want to concatenate with the url string.
What looks right to me but doesn't work is the following

``` javascript
this.$lightbox.find('.lb-link').on('click',function(){c.end();window.location='https://mydomain.com?=' + 
this.$lightbox.find('.lb-caption').html(this.album[this.currentImageIndex].title)
});
```

Anyone know how to get this string from the current title?
