### ISSUE TITLE
Cannot access normal image context menu

### ISSUE THREAD

**Issue by teo1978** [lokesh/lightbox2#524]
When you are viewing an image enlarged with LightBox, and you right-click on the image, the usual items like **"save image"** or **"open image in new tab"** don't come up in the context menu. This is because there's a div on top of the image, so you are right-clicking on it rather than on the image.

This is extremely annoying and kills standard usability features for no good reason.

**Comment by teo1978** [comment]
I've come up with a workaround for this, which is to apply the following stile **after lightbox.css**:
```css
.lb-image {
	border: solid 1px #888;
}

.lb-nav {
	position: static;
	overflow: visible;
	width: 0;
	height: 0;
}
.lb-nav a.lb-next {
	float: none;
	position: absolute;
	top: 0;
	right: 0;
	width: 25%;
	min-width: 60px;
}
.lb-nav a.lb-prev {
	float: none;
	position: absolute;
	top: 0;
	left: 0;
	width: 25%;
	min-width: 60px;
}
```
