### ISSUE TITLE
Image resizing issue

### ISSUE THREAD

**Issue by ironfrown** [lokesh/lightbox2#740]
Lightbox2 2.11.4 on Chrome+Firefox / Ubuntu 22.04

If an image does not fit the viewport, LB2 is checking which dimension is offending and fixes it.
However, after resizing the other dimension may still be too large to fit in a viewport, requiring scrolling.

To reproduce, take any horizontal image larger than the browser window and reduce the browser height significantly, 
LM2 will fit the width but the height will be clipped.

Attached below - web page before and after image click.
![LM2_before](https://github.com/lokesh/lightbox2/assets/6309054/e4324c6f-0ed1-4d35-8975-43e2c704f5e3)
![LM2_after](https://github.com/lokesh/lightbox2/assets/6309054/2bdd0914-4cad-4bb6-81c2-27ad2c04dff3)

**Comment by OGFaisalN** [comment]
I would say just use CSS to fix this easily, but sizing is definitely an issue I too encountered when using Lightbox 2, and it should be fixed. Small images need to enlarge (>= 75% of screen height) and large images need to shrink (>= 75% of screen height). Below is the CSS override I'm using.

```css
.lb-outerContainer {
    width: 90vw !important;
}

.lightbox .lb-image {
    width: 100% !important;
    height: unset !important;
}
```
